<?php

namespace Wmd\WatchMyDeskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DeskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeskRepository extends EntityRepository
{
}