<?php

namespace Wmd\WatchMyDeskBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DeskCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeskCommentRepository extends EntityRepository
{
}