<?php

namespace Wmd\WatchMyDeskBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DeskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeskRepository extends EntityRepository
{
	public function getLastPosted($limit = 5)
	{
	    return $this->createQueryBuilder('d')
		    ->where('d.isEnabled = :enabled')
		    ->setParameter('enabled', true)
		    ->addOrderBy('d.updatedAt', "DESC")
		    ->addOrderBy('d.id', "DESC")
		    ->setMaxResults($limit);
	}
}